# Generated by Django 4.1.2 on 2022-10-19 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfdocument',
            name='file_name',
            field=models.CharField(default='somefile', max_length=64),
        ),
        migrations.AlterField(
            model_name='pdfdocument',
            name='document',
            field=models.FileField(upload_to='pdfs/'),
        ),
    ]
